### ISSUE TITLE
Setup DocSearch

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/docs.asciidoctor.org#7]
Following this guide: https://gitlab.com/antora/antora-ui-default/issues/44#note_68053321 ?

**Comment by mojavelinux** [comment]
Agreed, though I'd like to use our own index instead of relying on the one maintained by Algolia. That gives us more control and quicker turnaround. It does mean we'll have to run the indexer ourselves, but that's something we should be able to use CI to do.

**Comment by mojavelinux** [comment]
This is done. However, we're still on a trial plan. I have requested for us to be put on an OSS plan, but Algolia has not yet responded. (An alternative is to use the money from the collective to cover this infrastructure cost).

**Comment by Mogztter** [comment]
>  I have requested for us to be put on an OSS plan, but Algolia has not yet responded. (An alternative is to use the money from the collective to cover this infrastructure cost).

It's not helping but to be fair last time I asked they were very responsive :wink:

**Comment by mojavelinux** [comment]
I had the same experience last time. Not sure what happened this time. I might need to resubmit.

**Comment by mojavelinux** [comment]
As it turns out, they never received the request. I got in touch with support and now we're on the OSS plan.

The only remaining task now is to enable the indexer to run automatically. There are two ways to do this:

1. Trigger the indexer after the Netlify job completes
2. Run the indexer on a fixed schedule, perhaps every other day

The first approach runs the risk of running the indexer too frequently (and thus exceeding our quotas). The second can end up running the indexer unnecessarily. However, what we could do is check the last published data of the site and if it is less than a day old, then run the indexer. We would just need to add that logic to the activation step in the CI job.

**Comment by mojavelinux** [comment]
Here's the automation logic I'd like to start with:

* Run the indexer on a daily schedule, after the daily schedule for the site itself
* Only run the indexer if the last modified time of the site is within 24 hours (meaning it was modified since the last time the indexer ran)

That should avoid us overrunning our quota and having to worry about running the indexer manually. We can then improve that logic as time goes on.
